DROP TABLE IF EXISTS CHECK_IN;
DROP TABLE IF EXISTS SHARED_PAGE;

CREATE TABLE CHECK_IN (
  CHECK_IN_TIME  DATETIME(6)      NOT NULL,
  VERSION        INTEGER          NOT NULL,
  LATITUDE       DOUBLE PRECISION NOT NULL,
  LONGITUDE      DOUBLE PRECISION NOT NULL,
  MESSAGE_TEXT   VARCHAR(255),
  VISIBLE        BIT,
  SHARED_PAGE_ID VARCHAR(100),
  PRIMARY KEY (CHECK_IN_TIME)
)
  ENGINE = INNODB;

CREATE INDEX IDX_SHARED_PAGE_ID
  ON CHECK_IN (SHARED_PAGE_ID);

CREATE TABLE SHARED_PAGE (
  ID               VARCHAR(100) NOT NULL,
  SHARED_PAGE_NAME VARCHAR(100),
  PRIMARY KEY (ID)
)
  ENGINE = INNODB;

ALTER TABLE CHECK_IN
  ADD CONSTRAINT FK_SHARED_PAGE_CHECK_IN
FOREIGN KEY (SHARED_PAGE_ID)
REFERENCES SHARED_PAGE (ID);